# Script PowerShell para agregar racha rápidamente
# Uso: .\quick-add-streak.ps1 -Email "tu@email.com" -HabitTitle "Ejercicio" -Days 60

param(
    [Parameter(Mandatory=$true)]
    [string]$Email,
    
    [Parameter(Mandatory=$true)]
    [string]$HabitTitle,
    
    [Parameter(Mandatory=$false)]
    [int]$Days = 50
)

Write-Host "🔧 Agregando racha de $Days días..." -ForegroundColor Cyan
Write-Host "   Usuario: $Email" -ForegroundColor Gray
Write-Host "   Hábito: $HabitTitle" -ForegroundColor Gray
Write-Host ""

# Crear el SQL dinámicamente
$sql = @"
USE planner_db;
SET @user_email = '$Email';
SET @habit_title = '$HabitTitle';
SET @days_streak = $Days;

SELECT @user_id := id FROM users WHERE email = @user_email LIMIT 1;
SELECT @habit_id := id FROM habits WHERE user_id = @user_id AND title = @habit_title LIMIT 1;

INSERT INTO habit_completions (habit_id, completion_date)
SELECT @habit_id, DATE_SUB(CURDATE(), INTERVAL n DAY)
FROM (
    SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL 
    SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL
    SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
    SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
    SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL
    SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL
    SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
    SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL
    SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL
    SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
    SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL
    SELECT 60 UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64 UNION ALL
    SELECT 65 UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
    SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL SELECT 73 UNION ALL SELECT 74 UNION ALL
    SELECT 75 UNION ALL SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL SELECT 79 UNION ALL
    SELECT 80 UNION ALL SELECT 81 UNION ALL SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL
    SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL SELECT 88 UNION ALL SELECT 89 UNION ALL
    SELECT 90 UNION ALL SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL SELECT 94 UNION ALL
    SELECT 95 UNION ALL SELECT 96 UNION ALL SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99
) AS numbers
WHERE n < @days_streak
ON DUPLICATE KEY UPDATE completion_date = completion_date;

SELECT COUNT(*) as total_dias FROM habit_completions WHERE habit_id = @habit_id;
"@

# Ejecutar en el contenedor
$sql | docker exec -i planificador-db-dev mysql -u root -prootpassword

Write-Host ""
Write-Host "✓ Racha agregada exitosamente!" -ForegroundColor Green
Write-Host "  Recarga la aplicación para ver los cambios" -ForegroundColor Gray
